export const STATUS_FINISHED = 'STATUS_FINISHED';
export const STATUS_PROCESSING = 'STATUS_PROCESSING';
export const STATUS_IDLE = 'STATUS_IDLE';
export const STATUS_ERROR = 'STATUS_ERROR';

export const MESSAGE_START = 'START';
